# ===================================================================
# Continuous Integration & Auto-Publish
# for @nanawareajinkya/dual-listbox
# Built and maintained by Ajinkya Nanaware
# ===================================================================

name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*' # For auto-publish when version tags are pushed (e.g., v1.0.0)

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4️⃣ Run lint (non-blocking)
      - name: Run ESLint
        run: |
          npm run lint --if-present || echo "✅ Non-blocking lint warnings ignored."

      # 5️⃣ Build Angular library
      - name: Build Angular library
        run: npm run build:lib

      # 6️⃣ (Optional) Test placeholder
      - name: Skip tests (library only)
        run: echo "🧪 No unit tests configured — skipping."

      # 7️⃣ Upload dist as build artifact
      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dual-listbox-dist
          path: dist/dual-listbox/

  publish:
    name: Publish to npm (on tagged release)
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install and build
        run: npm ci --legacy-peer-deps && npm run build:lib

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/dual-listbox
          npm publish --access public
