# ===================================================================
# Continuous Integration & Auto-Publish
# for @nanawareajinkya/dual-listbox
# Built and maintained by Ajinkya Nanaware
# ===================================================================

name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*' # Auto-publish on version tags (e.g., v1.0.0)

jobs:
  build:
    name: Build & Verify
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run ESLint (non-blocking)
        run: |
          npm run lint --if-present || echo "✅ Non-blocking lint warnings ignored."

      - name: Build Angular library
        run: npm run build:lib

      - name: Skip tests (library only)
        run: echo "🧪 No unit tests configured — skipping."

      - name: Upload dist artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dual-listbox-dist
          path: dist/dual-listbox/

  publish:
    name: Publish to npm (on tagged release)
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          always-auth: true

      - name: Install and build
        run: npm ci --legacy-peer-deps && npm run build:lib

      - name: Verify build output and version
        run: |
          if [ ! -d "dist/dual-listbox" ]; then
            echo "❌ dist folder not found! Build failed or missing."
            exit 1
          fi

          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PKG_VERSION=$(node -p "require('./projects/dual-listbox/package.json').version")
          echo "📦 Tag version: $TAG_VERSION"
          echo "📦 Package version: $PKG_VERSION"

          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "❌ Version mismatch between tag and package.json"
            exit 1
          fi

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/dual-listbox
          npm publish --access public
